name: Build Java App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compile
        run: javac VulnerableApp.java

      - name: Run App
        run: echo "TestUser" | java VulnerableApp
